### ISSUE TITLE
Cardinality on type level

### ISSUE THREAD

**Issue by Bodigrim** [identicalsnowflake/cantor-pairing#7]
Is it possible to promote cardinality to the type level? Like,
```
data Cardinality = Finite Nat | Countable

class Cantor a where 
  type Measure a :: Cardinality
  ...
```
instead of 
```
data Cardinality = Finite Integer | Countable 

class Cantor where 
  cardinality :: Cardinality
  ...
```

This would allow to distinguish between finite and countable on type level, eliminating the need in deriving an additional `Finite` typeclass. Constraint `Finite a` would be simply `Measure a ~ Finite n`.

**Comment by identicalsnowflake** [comment]
This was how I tried to do it originally, but ran into problems and so pursued the current approach instead. Unfortunately, I don't actually remember what those problems were.

But yes, I'm not opposed to tracking cardinality at the type level.

One issue with the library in its current state, which I'm not sure even has a good solution, is that it's very easy to create obscenely large finite types (e.g., `IntSet`) where simply observing the cardinality is well beyond the ability of modern computing power. Ideally this would be less brittle than it is now (now you can't even use `cantorEnumeration` lazily because the cardinality isn't lazy, which is annoying). I've thought about moving to a `Z | S N` encoding, which I think should at least allow `cantorEnumeration` to be productive, but at the expense of other functionality (like the cardinality of `Int` now being too expensive to show). Perhaps there's other more exotic lazy numeric encodings that could be used?

In any case, if it's worth investigating moving cardinality to the type level, it's also worth investigating what kinds of numerical encodings are usable and whether they'd address any of the above concerns or whether they'd fail in the same or different ways.

**Comment by Bodigrim** [comment]
> Perhaps there's other more exotic lazy numeric encodings that could be used?

I drafted an example of a possibly suitable lazy encoding, which can be used instead of `Integer` in `Finite`, here: https://gist.github.com/Bodigrim/03cd9db334e4f84e141996859ed79884

```haskell
data Huge
  = Nat Natural
  | Add Huge Huge
  | Mul Huge Huge
  | Pow Huge Huge
```

It is perfectly able to check instantly that 

```haskell
> 10000000 < 2 `pow` (2 `pow` 32)
True
```

This is only a draft with a lot of things to improve though. I can spend some time polishing, if you find this useful.

**Comment by identicalsnowflake** [comment]
Seems to spin if both the left and the right are `Huge`, but that's probably a hard problem, though it would be nice if syntactically equal cases behaved well, e.g.,

```haskell
> 2 `pow` (2 `pow` 32) < 2 `pow` (2 `pow` 32)
```

But yes, I think this fits the cardinality use case -- even if `a < b` is only practically computable for "small" values of `a`, it at least allows the enumeration to be productive, and unlike `Z | S n`, we should still be able to show cardinalities like `2 ^ 32`.

Looks reasonable.

What polishing did you have in mind? I don't think `Huge` needs to appear in the public API, so it doesn't need to be perfect before merging - even in its current state, it looks strictly superior to what's there now.

**Comment by Bodigrim** [comment]
I've updated the gist to cover syntactically equal cases and a bit more:

```haskell
> let x = 2 `pow` (2 `pow` 32) in x `compare` (2 `pow` x)
LT 
```

> What polishing did you have in mind? 

It remains to write better tests (and probably debug!) and refactor `compareNat`.

> I don't think `Huge` needs to appear in the public API

Would not `Cardinality` look like `Finite Huge | Countable`?

**Comment by identicalsnowflake** [comment]
I'm happy with how all this turned out and pushed a new version to hackage including your changes.

**Comment by identicalsnowflake** [comment]
Now back to the original question: does it seem like this would translate to the type level? 😂

**Comment by Bodigrim** [comment]
No :) While technically doable, it does not make much sense to promote lazy numbers to the type level, because they are not in a normal form, so `Nat 4` and `Add 2 2` are incompatible types. Besides that, it seems that classes with associated type families do not play well with overlapping instances.
